"""CPU collector wiring with an explicitly synthetic completion, not model support."""

import copy

from proworksim.member_views import member_view
from proworksim.online_collection import collect_window
from proworksim.online_training import prepare_window, recipe_config
from proworksim.storage import digest, json_bytes


def test_real_world_collector_preserves_synthetic_transport_and_window_binding(tmp_path):
    class FixtureOwner:
        recipe = recipe_config()
        window_id = "fixture-window"
        calls = 0
        seeds = []

        def freeze_identity(self):
            return {"version": "shared-actor-identity-v0.13", "policy_version": "fixture-actor",
                    "adapter_sha256": digest(b"fixture-adapter"),
                    "base_manifest_sha256": digest(b"fixture-base"),
                    "inference_profile_sha256": digest(b"fixture-profile")}

        @property
        def transport(self):
            return self

        def reseed(self, seed, *, label):
            self.seeds.append({"seed": seed, "label": label})

        def complete(self, request, *, timeout_seconds):
            # This fixture checks record linkage only; it never asserts these
            # synthetic token IDs/logp were generated by a real language model.
            self.calls += 1
            assert request["temperature"] == self.recipe["temperature"]
            assert request["max_tokens"] == self.recipe["max_output_tokens"]
            assert {t["function"]["name"] for t in request["tools"]} >= {"read_alias", "read_version", "staff_done"}
            body = {"id": "fixture-completion", "model": request["model"],
                    "system_fingerprint": self.freeze_identity()["policy_version"],
                    "actor_identity": self.freeze_identity(), "online_window_id": self.window_id,
                    "choices": [{"index": 0, "finish_reason": "stop",
                                 "message": {"role": "assistant", "content": '{"kind":"done","reason":"synthetic fixture stop"}'}}],
                    "usage": {"prompt_tokens": 2, "completion_tokens": 1, "total_tokens": 3},
                    "token_trace": {"input_ids": [1, 2], "output_ids": [3], "input_mask": [0, 0],
                                    "output_mask": [1], "behavior_logprobs": [-0.5],
                                    "sampling_temperature": 0.7, "sampling_top_p": 1.0, "sampling_top_k": 0,
                                    "source": "actual generation token IDs and sampling logits, not retokenized text"}}
            return {"http_status": 200, "raw_body": json_bytes(body).decode(), "body": copy.deepcopy(body), "response_headers": {}}

    owner = FixtureOwner()
    entries = collect_window(owner, {"window_id": owner.window_id, "slots": [
        {"slot_id": "fixture-handoff", "case_id": "development-w0-handoff", "sampling_seed": 13}
    ]}, tmp_path / "collection")
    assert owner.calls == 1
    assert owner.seeds == [{"seed": 13, "label": "fixture-handoff"}]
    assert len(entries) == 1
    rollout = entries[0]["rollout"]
    assert rollout is not None
    assert entries[0]["reward"]["eligible"] is True
    assert entries[0]["reward"]["reward"] == 0
    assert rollout["work_validity"]["components"]["record"]["value"] is True
    view = member_view(rollout, "provider")
    assert view["complete_actor_trajectory"] is True
    assert len(view["decisions"]) == 1
    decision = view["decisions"][0]
    assert decision["policy_identity"]["config"]["weight_identity"] == owner.freeze_identity()
    assert decision["tokens"]["output_ids"] == [3]
    prepared = prepare_window(entries, owner.freeze_identity(), owner.window_id, owner.recipe)
    assert len(prepared["decisions"]) == 1
    assert prepared["decisions"][0]["reward"] == 0
