"""Cross business policy/source with three real review submission conditions.

Quality controls are initialization metadata, never model labels or remedies.
Different prepared submissions remain different exact situations for support.
"""

import copy

from ..storage import digest, json_bytes
from . import retail_work

VERSION = "retail-balanced-review-v0.18"
QUALITIES = ("correct", "wrong_count", "wrong_amount")


def registry():
    cases = []
    for original in retail_work.registry()["situations"]:
        qualities = QUALITIES if original["task"] == "review" else (None,)
        for quality in qualities:
            case = copy.deepcopy(original)
            identity = [VERSION, case["pool"], case["fact_position"], case["task"], quality]
            case.update(
                version=VERSION,
                case_id="retail-v18-" + digest(json_bytes(identity))[:16],
                prepared_submission=quality,
                original_source_case=original["case_id"],
            )
            # The genuine source and business policy stay identical across
            # quality variants. An opaque catalog name is supplementary only;
            # the actual cross is what removes the deterministic correlation.
            cases.append(case)
    return {
        "version": VERSION,
        "situations": cases,
        "source_family_count": 1,
        "review_factorial": "Each pool x source/policy fact x {correct,wrong_count,wrong_amount}; all generated by real write/build/submit operations.",
        "support_rule": "Different initial submitted products define different xi; never combine quality variants as methods.",
        "split_rule": "Original UCI customer/invoice pools unchanged. No label is placed in actor tasks, public policy, or source data; normal work products must still be inspected.",
    }


def case_spec(case_id):
    matches = [c for c in registry()["situations"] if c["case_id"] == case_id]
    if len(matches) != 1:
        raise ValueError("Unknown declared v0.18 retail situation")
    return copy.deepcopy(matches[0])


def resolve(pool, fact, task, quality=None):
    if task == "review" and quality not in QUALITIES:
        raise ValueError("Review requires an explicit host-only preparation control")
    if task != "review" and quality is not None:
        raise ValueError("Only prepared review tasks have a submission condition")
    rows = [
        c
        for c in registry()["situations"]
        if c["pool"] == pool
        and c["fact_position"] == fact
        and c["task"] == task
        and c["prepared_submission"] == quality
    ]
    if len(rows) != 1:
        raise ValueError("Unknown crossed condition")
    return copy.deepcopy(rows[0])


def build_balanced_case(case, root, *, assets_root=None):
    if isinstance(case, str):
        case = case_spec(case)
    if case != case_spec(case["case_id"]):
        raise ValueError("v0.18 case differs from its frozen full specification")
    case = copy.deepcopy(case)
    spec = retail_work.scenario(case, source_root=assets_root)
    spec["world"]["world_id"] = "uci-retail-balanced-review"
    spec["variation"]["review_design"] = VERSION
    return retail_work._build_prepared_case(case, root, declaration=spec, version=VERSION)
